= Filecoin: 一个去中心化存储网络
Protocol Labs

刘博(译)

2017-07-24

== 摘要

互联网正处在一场革命的中间阶段: 中心化的专有服务正在被去中心化的开放的服务所取代; 可验证的计算取代了信任主体; 弹性内容地址取代了脆弱的位置地址; 点对点算法市场取代了低效的单片服务. Bitcoin, Ethereum 和其他区块链网络已经证明了分散化交易总账的效用. 这些公开总账处理复杂的智能合约应用和交易价值数百亿美元的加密资产. 这些系统是互联网开放式服务的第一个实例, 参与者形成一个去中心化的网络, 为了收益提供有用的服务, 而且没有中央管理或信任方. IPFS通过去中心化网络本身证明了内容寻址的效用, 为全球 P2P 网络中使用的数十亿个文件提供服务. 他从仓库中解放数据, 节省网络分区, 离线工作, 路由审查, 并且为数字信息提供持久化.

Filecoin 是一个去中心的存储网络, 将云存储转化为一个算法市场. 这个市场运行在一个带有本地协议 token (也称为 "Filecoin")的区块链上, 并且矿工通过向客户提供存储来获得 token 收益. 相反地, 客户花费 Filecoin 来雇佣旷工来存储或者分发数据. 与比特币一样, Filecoin 矿工为了相当大的回报来挖区块, 但是 Filecoin 的挖矿算力与活跃存储成比例, 这直接为客户提供有用的服务(不像比特币挖矿, 其有用性仅限于维持区块链共识). 这位矿工提供了一个强大的刺激, 来尽可能多低手机存储空间, 并将其出租个客户. 该协议将这些积累的资源编织成世界上任何人都可以依靠的自愈存储网络. 网络通过复制和分散内容实现鲁棒性, 同时自动检测和修复复制失败. 客户可以选择复制参数, 来避免不同的威胁模型. 该协议的云存储网络还提供安全性, 因为内容在客户端端对端加密的, 而存储提供商无法访问解密密钥. Filecoin 作为一个激励层工作在 IPFS 之上, 可以为任何数据提供存储基础设施. 它对于分散数据, 构建和运行分布式应用程序以及实施智能合同特别有用.

这项工作:

* (a) 介绍 Filecoin 网络, 概述协议, 并详细介绍几个组件.
* (b) 形式化去中心存储网络(DSN)方案及其属性, 然后构造 Filecoin 作为一个 DSN.
* (c) 推出了一种新型的称为复制量证明的存储量证明方案, 可以允许证明任何数据副本都存储在物理上独立的存储中.
* (d) 推出了一种新型的有用的工作共识基于顺序的复制量证明和存储量证明作为算力的度量.
* (e) 形式化可验证市场, 并构建两个市场, 一个存储市场和一个检索市场, 分别管理数据如何从 Filecoin 写入和读取.
* (f) 讨论 Filecoin 使用的擦除编码方案, 如何检测失败, 以及网络如何自动自我修复.
* (g) 讨论用例, 与其他系统的连接以及如何使用该协议.

注意: Filecoin 是在构建中. 活跃的研究正在进行中, 并且新版本论文将会出现在 https://filecoin.io[^]. 如需意见和建议, 请通过 research@filecoin.io 联系我们.

== 1. 前言

Filecoin 是一个协议令牌, 其区块链运行在一个新颖的证明上, 称为空闲时间证明，其中区块由正在存储数据的矿工创建. Filecoin 协议提供一个数据存储和检索服务通过一个独立的存储提供商网络, 并不依赖单一的协作者. 在这里: (1) 客户付费来存储和检索数据. (2) 存储旷工通过租赁存储来获取 token. (3) 检索旷工通过服务数据来获取 token.

=== 1.1 基本要素

Filecoin 协议建立在 4 个新颖的组件上.

* 1. 去中心存储网络(DSN): 我们提供了一个独立存储供应商网络的抽象来租赁存储和检索服务(在第二节). 后来, 我们将 Filecoin 协议作为一个激励的, 可审计的和可验证的 DSN 构建(在第四节)

* 2. 新颖的存储证明: 我们展示两种新颖的存储证明(在第三节): (1) 复制量证明允许存储提供商证明数据已被复制到其自己的唯一专用物理存储. 强制唯一的物理副本使验证者能够检查证明者不会将多个数据副本重复数据放到同一存储空间中; (2) 空闲时间证明允许存储提供商证明他们在一定时间内存储了一些数据.

* 3. 可验证市场: 我们建模将存储请求和检索请求作为订单在两个由 Filecoin 网络运行的去中心的可验证市场(在第五节).
